services:
    db:
      image: mysql:5.7
      container_name: fastify_db
      volumes:
          - ./infrastructure/mysql/volumes:/var/lib/mysql # 永続化するときにマウントするdir
          - ./infrastructure/mysql/initdb.d:/docker-entrypoint-initdb.d # 初回実行
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: root